checks:
    php: true
filter:
    excluded_paths:
        - tests/*
        - examples/*
build:
   nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [php-scrutinizer-run]
    environment:
        php:
            version: 7.1
    tests:
        override:
            -
                command: ./vendor/bin/phpunit --coverage-clover=.coverage
                coverage:
                    file: .coverage
                    format: php-clover
