checks:
    php: true
filter:
    excluded_paths:
        - tests/*
        - examples/*
build:
    environment:
        php:
            version: 7.1
    tests:
        override:
            -
                command: phpunit --coverage-clover=.coverage
                coverage:
                    file: .coverage
                    format: php-clover
